version: "3.7"

services:
  coders-board:
    container_name: coders-board
    build:
      args:
        NODE_ENV: development
        IMAGE_BASE_DEV: node:alpine
        IMAGE_BASE_PROD: node:alpine
      context: .
      target: development

    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - coders-board-network
    stdin_open: true
    tty: true
    command: /bin/sh
networks:
  coders-board-network:
    name: coders-board-network
